-- =============================================================================
-- Módulo de sensores IoT para Supabase (PostgreSQL)
-- Ejecutar en el SQL Editor de Supabase o como migración.
-- =============================================================================

-- Extensión UUID (habitualmente ya activa en Supabase)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- -----------------------------------------------------------------------------
-- Tabla: devices
-- Un dispositivo (sensor) asociado a una parcela y a un usuario (RLS).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.devices (
  id            uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  name          text NOT NULL,
  type          text NOT NULL CHECK (type IN ('soil_moisture', 'weather_station', 'temperature', 'humidity', 'other')),
  parcel_id     uuid NULL,  -- FK a tu tabla de parcelas (ej. public.parcel o public.parcela)
  user_id       uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  battery_level  smallint NULL CHECK (battery_level IS NULL OR (battery_level >= 0 AND battery_level <= 100)),
  status        text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'offline', 'maintenance')),
  last_seen     timestamptz NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- Índices para listados y filtros por usuario/parcela
CREATE INDEX IF NOT EXISTS idx_devices_user_id   ON public.devices(user_id);
CREATE INDEX IF NOT EXISTS idx_devices_parcel_id ON public.devices(parcel_id);
CREATE INDEX IF NOT EXISTS idx_devices_status    ON public.devices(status);
CREATE INDEX IF NOT EXISTS idx_devices_last_seen ON public.devices(last_seen);

COMMENT ON TABLE public.devices IS 'Dispositivos/sensores IoT; RLS por user_id.';
COMMENT ON COLUMN public.devices.parcel_id IS 'Opcional: referencia a la tabla de parcelas (crear FK cuando exista).';

-- -----------------------------------------------------------------------------
-- Tabla: telemetry
-- Series temporales por dispositivo. Crece mucho → ver recomendaciones al final.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.telemetry (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id       uuid NOT NULL REFERENCES public.devices(id) ON DELETE CASCADE,
  timestamp       timestamptz NOT NULL DEFAULT now(),
  temperature     double precision NULL,  -- °C
  humidity        double precision NULL, -- % 0-100
  soil_moisture   double precision NULL, -- % o m³/m³ según sensor
  pressure        double precision NULL, -- hPa
  created_at      timestamptz NOT NULL DEFAULT now()
);

-- Índice compuesto para consultas por dispositivo y rango de fechas (muy usado)
CREATE INDEX IF NOT EXISTS idx_telemetry_device_timestamp
  ON public.telemetry (device_id, timestamp DESC);

-- Índice BRIN por tiempo: poco tamaño, muy bueno para rangos por fecha en datos ordenados
CREATE INDEX IF NOT EXISTS idx_telemetry_timestamp_brin
  ON public.telemetry USING BRIN (timestamp);

COMMENT ON TABLE public.telemetry IS 'Telemetría de sensores; considerar particionamiento o TimescaleDB si crece mucho.';

-- -----------------------------------------------------------------------------
-- RLS (Row Level Security): cada usuario solo ve sus sensores
-- -----------------------------------------------------------------------------
ALTER TABLE public.devices  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telemetry ENABLE ROW LEVEL SECURITY;

-- Políticas para devices: acceso por user_id = auth.uid()
CREATE POLICY "users_select_own_devices"
  ON public.devices FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "users_insert_own_devices"
  ON public.devices FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "users_update_own_devices"
  ON public.devices FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "users_delete_own_devices"
  ON public.devices FOR DELETE
  USING (auth.uid() = user_id);

-- Políticas para telemetry: solo si el dispositivo es del usuario
CREATE POLICY "users_select_own_telemetry"
  ON public.telemetry FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.devices d
      WHERE d.id = telemetry.device_id AND d.user_id = auth.uid()
    )
  );

CREATE POLICY "users_insert_own_telemetry"
  ON public.telemetry FOR INSERT
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.devices d
      WHERE d.id = telemetry.device_id AND d.user_id = auth.uid()
    )
  );

-- Opcional: permitir que el backend inserte telemetría con service_role (no sujeto a RLS)
-- Por defecto, los inserts desde el cliente pasan por RLS; si los sensores envían vía API con JWT de usuario, esto basta.

-- -----------------------------------------------------------------------------
-- Trigger: actualizar updated_at en devices
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS devices_updated_at ON public.devices;
CREATE TRIGGER devices_updated_at
  BEFORE UPDATE ON public.devices
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- RECOMENDACIONES: telemetry crece mucho
-- =============================================================================
--
-- 1) ÍNDICES BRIN (ya creados arriba)
--    - Ventaja: poco espacio, buenos para consultas por rango de tiempo.
--    - Útil cuando los datos se insertan por tiempo y haces muchas consultas
--      del tipo "últimos 7 días" o "entre fecha A y B".
--    - Recomendado como primera medida.
--
-- 2) PARTICIONAMIENTO POR FECHA (PostgreSQL nativo)
--    - Si telemetry supera ~10–50M filas, plantéate particionar por mes/año.
--    - Ejemplo (descomentar y adaptar si lo usas):
--
-- ALTER TABLE public.telemetry RENAME TO telemetry_old;
-- CREATE TABLE public.telemetry (
--   LIKE public.telemetry_old INCLUDING DEFAULTS INCLUDING CONSTRAINTS
-- ) PARTITION BY RANGE (timestamp);
-- CREATE TABLE telemetry_2025_01 PARTITION OF public.telemetry
--   FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');
-- -- ... más particiones por mes; migrar datos desde telemetry_old.
--
-- 3) TIMESCALEDB (si está disponible en tu proyecto Supabase)
--    - En Supabase: Dashboard → Database → Extensions → "timescaledb".
--    - Convierte telemetry en hypertable por timestamp para compresión y
--      particionado automático. Ejemplo (ejecutar después de crear la tabla):
--
-- CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
-- SELECT create_hypertable('public.telemetry', 'timestamp',
--   chunk_time_interval => INTERVAL '1 month',
--   if_not_exists => TRUE
-- );
--
-- Resumen: empieza con BRIN; si el volumen crece, añade particionamiento
-- o TimescaleDB según lo que tengas disponible.
